
# Thrust and Angle to motor and servo signal: This code converts the desired thrust and angle
# into corresponding motor and servo signals.

# For thrust, the function takes the desired thrust from motor (N) and translates it to
# the corresponding input signal for the boat motor on a scale from -1 to 1
# (there is no need to reverse, so only positive signals are considered in practice). 
# essentially using linear interpolation to map the thrust range to the motor signal range.

# --- Prop Params
from math import pi


moment_arm = 0.2 # moment arm of the prop about the ship's Longitudinal Center of Flotation (or COM)
thrust_coeff = 1.2 ### this is a guess. VERIFY THIS!!
prop_diameter = 0.1 # meters
max_prop_angle = pi/4 # when servo set to 0. --- EYEBALLED THIS NUMBER. (prop angle is zero straight ahead, positive when thrust is to the right.)
min_prop_angle = -pi/4 # when servo set to 180 --- EYEBALLED THIS NUMB  ER.
# for PRB282088 motor
motor_wattage = 300 # [W] estimated from 11.1 V battery at 30 A (from ESC)
motorprop_eff = 0.1 # assume 10% efficiency from electrical power input to motor and thrust generated by prop
motor_db = 0.15 # deadband measured to be +/- 0.15 imperically.



min_thrust = 0.5; # measured thrust at 0.15 motor_sig
half_thrust = 1; # measured thrust at 0.5 motor_sig


def thrust_angle_to_motor_servo(thrust, prop_angle):
    servo_max = 180
    servo_range = 180
    
   # new
    # motor_sig = 0.5 - ((thrust - min_thrust) / (half_thrust - min_thrust) * 0.5 * motor_db)
    A = 0.942715
    B = 0.0916248
    motor_sig = A*thrust**(1/2)+B # from emperical system ID (R^2 = 0.9977)

    servo_sig = servo_max - servo_range * (prop_angle - min_prop_angle) / (max_prop_angle - min_prop_angle)
    return motor_sig, servo_sig

